<?php
/**
 * ProductTagRequestTest
 *
 * PHP version 8.1
 *
 * @package  Lintrading
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 產品管理 API
 *
 * 電子商務系統中的產品管理 API。
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Lintrading\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProductTagRequestTest Class Doc Comment
 *
 * @description ProductTagRequest
 * @package     Lintrading
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductTagRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductTagRequest"
     */
    public function testProductTagRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tagIds"
     */
    public function testPropertyTagIds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
